### ISSUE TITLE
The file Google Account Manager 4.3.3 is not available

### ISSUE THREAD

**Issue by it-praktyk** [cobalt232/playstore#2]
![selection_003](https://cloud.githubusercontent.com/assets/4910261/12538124/695a780c-c2d1-11e5-841a-cc1a049fba05.jpg)

**Comment by cobalt232** [comment]
Fixed
Thanks for reporting.
regards!
----Ursprüngliche Nachricht----
Von : notifications@github.com
Datum : 24/01/2016 - 19:34 (MZ)
An : playstore@noreply.github.com
Betreff : [playstore] The file Google Account Manager 4.3.3 is not available (#2)

**Comment by it-praktyk** [comment]
Thank you.
