### ISSUE TITLE
Only horizontal green progress line

### ISSUE THREAD

**Issue by NikNik77771** [cobalt232/playstore#6]
Hello
I use you soft for a long time and was very satisfied to have some useful android apps on my blackberry. Unfortunately, 16 Dec 2017 all android apps stopped to launch. I see only horizontal green progress line. I remember that I had this problem before. It was resolved buy updating you software. Please, make new update!

**Comment by cobalt232** [comment]
It's an issue of the Android Runtime that's baked into OS10. Please visit the CrackBerry forums to get some help.most likely you'll have to update your OS.

**Comment by NikNik77771** [comment]
I have last development version of OS. It was updated by USB cable.

**Comment by cobalt232** [comment]
Development versions are not suitable for production devices. You must install a release version of the OS.
